name: Exploring and secrets

on:
    push

env:
    CONTAINER_REGISTERY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Docker Build
              run: echo docker build -t $CONTAINER_REGISTERY/${{ vars.username }}/$IMAGE_NAME:latest

            - name: Docker login
              run: echo docker login --username=${{ vars.username }} --password=${{ secrets.password }}
            
            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTERY/$username/$IMAGE_NAME:latest
    deploy:
        needs: docker
        runs-on: ubuntu-latest

        steps:
            - name: docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTERY/${{ vars.username }}/$IMAGE_NAME:latest